baseURL: /
languageCode: 'en-gb'
title: SIMON APEN-SADLER 
publishDir: docs
theme:
- github.com/Mitrichius/hugo-theme-anubis

paginate: 10
# disqusShortname: "yourdiscussshortname"
# googleAnalytics: "G-12345"
enableRobotsTXT: true

menu:
  main:
  - identifier: archive 
    name: Archive 
    title: Archive 
    url: /posts/
    weight: 2
  - identifier: about 
    name: About 
    title: About 
    url: /about/
    weight: 1
  - identifier: Categories 
    name: Categories 
    title: Categories 
    url: /tags/
    weight: 3

params:
  author: "Simon Apen-Sadler"
  # email: mail@example.org # used for microformats
  # avatar: "/images/me.png" # used for microformats
  description: "DevOps, SRE and tech blog"
  # Uncomment if you need this
  # images:
  #   - images/og-featured.png # relative path to "static" directory
  # customCSS:
  #   - css/my.css # relative path to "assets" directory (don't use main.css filename)
  # customJS:
  #   - js/main.js # relative path to "assets" directory
  dateFormat: "2006-01-02"
  paginationSinglePost: true
  style: light
  readMore: true
  disableSummary: false
  copyCodeButton: true # true by default
  rssAsSocialIcon: true
  # utteranc.es support
  utterancesRepo: ""  # mandatory
  utterancesTheme: "" # optional
  utterancesIssue: "" # optional
  utterancesLabel: "" # optional
  # isso support
#   isso:
#     enabled: true # mandatory
#     data: "https://comments.example.com/" # mandatory
#     jsLocation: "https://comments.example.com/js/embed.min.js" # mandatory
#     css: true # optional
#     lang: "de" # optional
#     replyToSelf: true # mandatory
#     requireAuthor: true # mandatory
#     requireEmail: true # mandatory
#     id: "thread-id" # optional
#     avatar: true # optional
#     avatar-bg: "#f0f0f0" # optional
#   webmentions:
#     url: https://yourdomain.com/webemntions/receive
#     login: hugo-theme-anubis
#     pingback: true
  social:
  - id: github
    name: sapensadler
  - id: linkedin
    name: sapensadler
#  - id: hugo
#    url: "https://gohugo.io/"
#    icon: "hugo"

markup:
  goldmark:
    renderer:
      unsafe: true # enable raw HTML in Markdown
